grpo_config = """
### model
model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct
adapter_name_or_path: saves/llama3-8b/lora/sft

### method
stage: grpo
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: comparison_gpt4_en
template: llama3
cutoff_len: 1024
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/llama3-8b/lora/grpo
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 5.0e-7
num_train_epochs: 1.0
max_grad_norm: 1.0
lr_scheduler_type: cosine
warmup_steps: 100

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500

### grpo
grpo_beta: 0.1
grpo_group_size: 4
"""